services:
  welldanet:
    container_name: welldanet_app
    image: ghcr.io/mr-devloper005/welldanet.com:latest
    env_file:
      - .env
    restart: always
    ports:
      - "127.0.0.1:3026:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
